apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mz
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:sikiryl/argo-app.git
    targetRevision: main
    path: deployments
  destination:
    server: https://kubernetes.default.svc
    namespace: default